version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY)
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME .
  build:
    commands:
      - echo Tagging the Docker image...
      - docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $ECR_REGISTRY/$IMAGE_NAME:latest
      - echo Deploying to EKS...
      - kubectl apply -f deployment.yaml

artifacts:
  files:
    - deployment.yaml
