version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "058264559032"
    AWS_DEFAULT_REGION: "us-east-1"
    IMAGE_REPO_NAME: "myhtml-app"
    KUBERNETES_NAMESPACE: "default"

phases:
  install:
    commands:
      - echo "Installing dependencies"
  pre_build:
    commands:
      - echo "Setting environment variables"
      - echo "$AWS_ACCOUNT_ID"
      - echo "$AWS_DEFAULT_REGION"
      - echo "Logging into Amazon ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo "Image pushed to ECR"
      - echo "Deploying to Kubernetes"
      - kubectl apply -f manifest/deployment.yaml --namespace $KUBERNETES_NAMESPACE

artifacts:
  files:
    - '**/*'
  discard-paths: yes
