apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: APP_NAME
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
      - name: APP_NAME
        image: your-aws-account-id.dkr.ecr.us-east-1.amazonaws.com/aws-html-app:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  namespace: default
spec:
  selector:
    app: APP_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
